
DROP TABLE [MODULE_NAME].TMUTATION CASCADE CONSTRAINTS;

DROP TABLE [MODULE_NAME].TMUTATION_MODULE CASCADE CONSTRAINTS;

DROP TABLE [MODULE_NAME].TMUTATION_OPERATIONS CASCADE CONSTRAINTS;

DROP TABLE [MODULE_NAME].TMUTATION_OPERATORS CASCADE CONSTRAINTS;

DROP TABLE [MODULE_NAME].TMUTATION_CONFIG CASCADE CONSTRAINTS;

DROP TABLE [MODULE_NAME].TMUTATION_TESTCASE CASCADE CONSTRAINTS;

DROP TABLE [MODULE_NAME].TMUTATION_TESTCASE_EXEC CASCADE CONSTRAINTS;
